### ISSUE TITLE
Error: mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed: [strict_dynamic_mapping_exception] mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed

### ISSUE THREAD

**Issue by sewalita** [ppadovani/KibanaNestedSupportPlugin#58]
Plugin version: 5.6.4-1.0.1
Kibana version: 5.6.4
Other Plugin in Kibana :  X-pack version 5.6.4

Steps to reproduce

1) Create an index user/profile with the following mapping
{
"user": {
"mappings": {
"profile": {
"properties": {
"age": {"type": "short"},
"user_id": {"type": "long"},
"gender": {"type": "keyword"},
"activity": {
"type": "nested",
"properties": {
"activity_date": {"type": "date"},
"activity_type": {"type": "keyword"},
"channel": {"type": "keyword"}
}
}
}
}
}
}
}

2) Use esStorageHandler to load data to the index
CREATE TABLE es_user  (
user_id string,
age int,
gender string,
activity array <STRUCT
<activity_date : timestamp,
activity_type :string,
channel :string>>
)
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES (
'es.resource'='user/profile',
'es.nodes'='localhost',
'es.port'='9200',
'es.net.http.auth.user'='user',
'es.net.http.auth.pass'='pwd',
'es.net.ssl'='true'
);

3) Load data into the es_user table using a Hive INSERT statement
INSERT INTO table es_user ...

4) Add the Index Pattern
and activity.activity_date as the Time Filter

Error is thrown saying
mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed: [strict_dynamic_mapping_exception] mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed

**Comment by ppadovani** [comment]
At first glance, you have a typo in either your mapping or the storage handler. In your mapping you specify the nested object to be called 'activity' and yet in the storage handler you call it 'activity_nested'.  These two different names will cause the error you are seeing if your mapping/index is set to strict.

**Comment by sewalita** [comment]
That was a typo in the comment. Updated it.
With or without the mapping the error remains.

**Comment by sewalita** [comment]
It appears on the Kibana > Management on adding Index pattern

**Comment by ppadovani** [comment]
Ok, thanks.. I know what to look for now. I'll setup an environment and work on duplicating this so I can track it down.

**Comment by ppadovani** [comment]
Ok... I can't seem to reproduce your issue. I tried the following:

Scenario 1
- Deleted .kibana index
- started Kibana without the plugin
- created the index with nested objects
- restarted Kibana with the plugin
- turned on nested support

Scenario 2
- Left Kibana running from scenario 1
- deleted the index pattern from Kibana 
- re-added the index pattern for the nested docs
- turned the nested support on

Can you try and figure out the steps needed to reproduce this issue?

Thanks!

**Comment by ppadovani** [comment]
Oh wait... just saw that you have x-pack installed... I did not test with that.... let me get back to you.

**Comment by ppadovani** [comment]
Ok.. I think I know what the issue is. This error will happen if there is no .kibana index in place after you have installed this plugin. That is, this plugin requires that Kibana has been started at least ONCE prior to install. When this plugin starts it will update the .kibana index mapping, if the index isn't there it isn't able to modify it, and when you try and turn on nested for an index you will get that error.

Please try and restart kibana, then active nested support.

**Comment by sewalita** [comment]
I have restarted Kibana after adding the index to the Index Pattern, but did not help.

Am using the plugin version https://github.com/ppadovani/KibanaNestedSupportPlugin/releases/tag/5.6.4-1.0.1

It does not state that it supports x-pack
Could that be the issue?

**Comment by ppadovani** [comment]
I installed x-pack on my 5.6.4, both Elasticsearch and Kibana, and had no issues... 

Is there an output/error on the console for Kibana during startup?

**Comment by sewalita** [comment]
I do not  see any error message on Kibana startup. 

There is a .kibana-sndbx  index that has the index-patterns. Should I delete that?
For the indices on which the the error appears, it does not allow to check/uncheck the Nested Enabled checkbox against those  indices

**Comment by sewalita** [comment]
Here's the error message

Error: mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed: [strict_dynamic_mapping_exception] mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed
exports.SavedObjectsClient</<.value/<@https://dlawosdg533410o.r1-core.r1.aig.net:5601/bundles/commons.bundle.js?v=15571:110:29394
processQueue@https://dlawosdg533410o.r1-core.r1.aig.net:5601/bundles/commons.bundle.js?v=15571:38:23621
scheduleProcessQueue/<@https://dlawosdg533410o.r1-core.r1.aig.net:5601/bundles/commons.bundle.js?v=15571:38:23888
$RootScopeProvider/this.$get</Scope.prototype.$eval@https://dlawosdg533410o.r1-core.r1.aig.net:5601/bundles/commons.bundle.js?v=15571:39:4607
$RootScopeProvider/this.$get</Scope.prototype.$digest@https://dlawosdg533410o.r1-core.r1.aig.net:5601/bundles/commons.bundle.js?v=15571:39:2343
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://dlawosdg533410o.r1-core.r1.aig.net:5601/bundles/commons.bundle.js?v=15571:39:5026
done@https://dlawosdg533410o.r1-core.r1.aig.net:5601/bundles/commons.bundle.js?v=15571:37:25016
completeRequest@https://dlawosdg533410o.r1-core.r1.aig.net:5601/bundles/commons.bundle.js?v=15571:37:28702
createHttpBackend/</xhr.onload@https://dlawosdg533410o.r1-core.r1.aig.net:5601/bundles/commons.bundle.js?v=15571:37:29634

**Comment by sewalita** [comment]
Resolved the issue. 
There was a conflict with another instance of Kibana without the plugin sharing the same ES cluster.

**Comment by pavolloffay** [comment]
I get the same issue when I install the plugin in Dockerfile. 

> I had this exact same issue. I was running Kibana from docker and installing this plugin as part of the docker container build

How can I resolve it when I run kibana from docker? 

```
FROM docker.elastic.co/kibana/kibana:5.6.9

RUN bin/kibana-plugin install https://github.com/ppadovani/KibanaNestedSupportPlugin/releases/download/5.6.9-1.0.2/nested-fields-support-5.6.9-1.0.2.zip
```

**Comment by ppadovani** [comment]
I'll take another look at this and see if I can find a way around the restriction on having Kibana run once before installing the plugin.

**Comment by pavolloffay** [comment]
This might help you to reproduce https://github.com/pavolloffay/jaeger-kibana

**Comment by ppadovani** [comment]
I know precisely where in the code the issue is... it is just a question of how to resolve it... I can duplicate it without using a docker container as well.. I just never considered it a serious enough limitation, obviously I was wrong. :-)

**Comment by kutoga** [comment]
I have the same issue with the plugin version 6.3.1-1.0.1.

**Comment by ppadovani** [comment]
@kutoga I'll be back porting this fix to all of my supported versions over the next few days depending on real life workload. Worst case I'll crank them out this weekend. I'll close this issue when I've finished the ports.

**Comment by kutoga** [comment]
Ok, thanks:-)

**Comment by ppadovani** [comment]
This is fixed for all 5.x versions and 6.0. Starting in 6.1, Kibana doesn't create the .kibana index on startup, and instead only on demand when you first try and create an index pattern. I'm going to have to hook into this process so finish this back port will take a bit more time for the remaining 6.1-6.3 releases.

**Comment by ppadovani** [comment]
Fixed and ported to all releases.

**Comment by pavolloffay** [comment]
thanks @ppadovani

**Comment by bphenriques** [comment]
Hello,

I am still having this issue. I following this issue and this [one](https://github.com/ppadovani/KibanaNestedSupportPlugin/issues/45).

**Environment:**
- Kubernetes deployment
- Elasticsearch 6.3.0
- Kibana 6.3.2 (also happened in 6.3.0)

**Steps to reproduce:**
- Deploy Kibana.
- Set up index-pattern.
- Install plugin:
```
  # Kibana 6.3.0
  ./bin/kibana-plugins install https://github.com/ppadovani/KibanaNestedSupportPlugin/releases/download/6.3.0-1.0.3/nested-fields-support-6.3.0-1.0.3.zip
```

```
 # Kibana 6.3.2
 ./bin/kibana-plugins install https://github.com/ppadovani/KibanaNestedSupportPlugin/releases/download/6.3.2-1.0.0/nested-fields-support-6.3.2-1.0.0.zip
```
- Restart Kibana (delete Pod).
- Install plugin.
- Enable nested fields for the index-pattern I have set up previously.
- Refresh the index pattern.

**Note:**
Also noticed that when I enable the nested field and come back to that same tab, that same setting is not enabled.

![peek 2018-08-30 12-08](https://user-images.githubusercontent.com/4727729/44848137-94943400-ac4d-11e8-876b-3ab3990fa0c9.gif)

**Comment by ppadovani** [comment]
Your issue is the refreshing of the index. When you refresh the index it wipes the index pattern document from the kibana index and replaces it with a fresh copy. This will reset the nested flag that this plugin injects into that index pattern object. If you hit refresh, you must go back and re-enable the nested flag.

**Comment by bphenriques** [comment]
> Your issue is the refreshing of the index. When you refresh the index it wipes the index pattern document from the kibana index and replaces it with a fresh copy. This will reset the nested flag that this plugin injects into that index pattern object. If you hit refresh, you must go back and re-enable the nested flag.

If you look at the gif I shared, I provide an example where I do not refresh the index and the flag does resets.

**Comment by ppadovani** [comment]
Sorry.. I must have missed that... Can you do me a favor, and pull the index pattern document from the .kibana index that aligns with your index? You can chop out the fields, I'm more interested in a top level attribute/field called 'nested' and if it is there and what the value is. 

I intend to spend some time this weekend working on some enhancements, I'll take a look at this as well and see if I can find a way to reproduce it.

**Comment by bphenriques** [comment]
@ppadovani Thank you for the quick feedback. Sure. However I did not find any attribute/field called `nested`. Check what what I did below.

1. Deleted .kibana index
2. Restarted Kibana
3. Created the index-pattern
4. `curl -X GET "localhost:9200/.kibana/_search"`
5. Extracted the document with id `index-pattern:870ef960-ac65-11e8-939d-0fa619a0dfbc`

The `source` field did not contain any mention to `nested`. However, if it helps, I can give a structure of the document:
```
{
    ...
    "fields": { 
          "value": 10,
          /* other regular fields */
    }
    "system": {
         /* regular fields */
         "nestedTypeA": [ { A_1 }, { A_2 }, ..., { A_N } ]  // nested type
         "nestedTypeB": [ { B_1 }, { B_2 }, ..., { B_N } ]  // nested type
    }
}
```

In my use case I am want buckets over `system.nestedTypeA.name` which is nested. And that nested field is in the `system` field.

I can give you more information that you think it is relevant.

**Comment by ppadovani** [comment]
In your steps above, did you also set the nested setting before you pulled
from the kibana index?

**Comment by bphenriques** [comment]
Yep

`GET /test/_mapping/_doc`:

```
...
          "fields": {
            "properties": {
              "value": {
                "type": "long"
              },
...

              "nestedTypeA": {
                "type": "nested",
...

             "nestedTypeB": {
                "type": "nested",

...
```

If you find it hard to have a complete picture of my use-case let me know so I can group up everything without renaming/adjusting field names :)

**Comment by bphenriques** [comment]
I misunderstood your question.

So I redid the steps, and before I submit `curl -X GET "localhost:9200/.kibana/_search"`, I checked the "nested" checkbox. 

![image](https://user-images.githubusercontent.com/4727729/44863579-6d515d00-ac75-11e8-8aed-39fb77297bfe.png)

The behavior I described before (it resets after I change the tab) still maintains. Checked the index-pattern document after toggling the box and it still does not contain any "nested" reference except on the name of the fields as expected.

Edit: checked the document before changing the tab

**Comment by ppadovani** [comment]
Ok.. so this sounds like the plugin did not update the mapping for the .kibana index to include the new nested field. That particular index is set to strict, so this plugin, on startup, updates the mapping.  Lets open a new issue for this. I think what needs to happen is to have the plugin attempt to set the nested flag, and if it is unable to, it updates the .kibana mapping, then tries again. This also solves an edge case where someone may delete the kibana index but not restart kibana so the plugin doesn't get a chance to update the mapping on startup.

**Comment by bphenriques** [comment]
@ppadovani I can describe my use-case in the new issue. In your opinion, what is the best name for the new issue?

**Comment by ppadovani** [comment]
Here ya go: "Custom Kibana mapping change should be more resilient."
